<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GitGat.Tests</RootNamespace>
    <AssemblyName>GitGat.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/GitGat.Domain/GitGat.Domain.csproj" />
    <ProjectReference Include="../../src/GitGat.Application/GitGat.Application.csproj" />
    <ProjectReference Include="../../src/GitGat.Infrastructure/GitGat.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
</Project>
