<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GitGat.Infrastructure</RootNamespace>
    <AssemblyName>GitGat.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GitGat.Domain/GitGat.Domain.csproj" />
    <ProjectReference Include="../GitGat.Application/GitGat.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
</Project>
